// One-off image pipeline: source JPGs -> AVIF + WebP at 3 widths, plus a typed manifest.
// Run with `npm run images`. Sources are read from assets-src/ (photos kept for reference live in assets-src/originals/ and are skipped).
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, parse } from 'node:path'
import sharp from 'sharp'

const SRC_DIRS = ['assets-src']
const OUT_DIR = 'public/img'
const MANIFEST = 'src/data/images.ts'

// Per-image widths. The hall artwork renders at most ~380 css px wide, so 1200 covers 3x screens.
const WIDTHS = { bagibagi: [400, 800, 1200], profile: [480, 720, 960, 1600], default: [480, 960, 1600] }
const QUALITY = { avif: 50, webp: 72 }

mkdirSync(OUT_DIR, { recursive: true })

const sources = new Map()
for (const dir of SRC_DIRS) {
  if (!existsSync(dir)) continue
  for (const file of readdirSync(dir)) {
    if (!/\.jpe?g$/i.test(file)) continue
    const key = parse(file).name.toLowerCase().replace(/[^a-z0-9]+/g, '-')
    if (!sources.has(key)) sources.set(key, join(dir, file))
  }
}

const entries = []
for (const [key, path] of sources) {
  const base = sharp(path).rotate() // apply EXIF orientation
  const { data, info } = await base.clone().toBuffer({ resolveWithObject: true })
  const ratio = info.height / info.width
  const widths = (WIDTHS[key] ?? WIDTHS.default).filter((w) => w <= info.width)
  const out = { avif: [], webp: [] }

  for (const w of widths) {
    for (const fmt of ['avif', 'webp']) {
      const name = `${key}-${w}.${fmt}`
      await sharp(data).resize({ width: w })[fmt]({ quality: QUALITY[fmt] }).toFile(join(OUT_DIR, name))
      out[fmt].push({ w, url: `/img/${name}`, kb: Math.round(statSync(join(OUT_DIR, name)).size / 1024) })
    }
  }

  const largest = widths.at(-1)
  entries.push({
    key,
    width: largest,
    height: Math.round(largest * ratio),
    src: out.webp.at(-1).url,
    avif: out.avif.map((v) => `${v.url} ${v.w}w`).join(', '),
    webp: out.webp.map((v) => `${v.url} ${v.w}w`).join(', '),
  })
  console.log(key.padEnd(10), out.avif.map((v) => `${v.w}:${v.kb}KB`).join('  '), '| webp', out.webp.map((v) => `${v.w}:${v.kb}KB`).join('  '))
}

const body = entries
  .map((e) => `  '${e.key}': {\n    src: '${e.src}',\n    width: ${e.width},\n    height: ${e.height},\n    avif: '${e.avif}',\n    webp: '${e.webp}',\n  },`)
  .join('\n')

writeFileSync(
  MANIFEST,
  `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\nimport type { ResponsiveImage } from './types'\n\nexport const IMAGES = {\n${body}\n} satisfies Record<string, ResponsiveImage>\n\nexport type ImageKey = keyof typeof IMAGES\n`,
)
console.log(`wrote ${MANIFEST}`)
