// Generated by scripts/optimize-images.mjs. Do not edit by hand.
import type { ResponsiveImage } from './types'

export const IMAGES = {
  'bagibagi': {
    src: '/img/bagibagi-1200.webp',
    width: 1200,
    height: 1500,
    avif: '/img/bagibagi-400.avif 400w, /img/bagibagi-800.avif 800w, /img/bagibagi-1200.avif 1200w',
    webp: '/img/bagibagi-400.webp 400w, /img/bagibagi-800.webp 800w, /img/bagibagi-1200.webp 1200w',
  },
  'profile': {
    src: '/img/profile-1600.webp',
    width: 1600,
    height: 2000,
    avif: '/img/profile-480.avif 480w, /img/profile-720.avif 720w, /img/profile-960.avif 960w, /img/profile-1600.avif 1600w',
    webp: '/img/profile-480.webp 480w, /img/profile-720.webp 720w, /img/profile-960.webp 960w, /img/profile-1600.webp 1600w',
  },
} satisfies Record<string, ResponsiveImage>

export type ImageKey = keyof typeof IMAGES
